### ISSUE TITLE
Add 360 video component

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/vr-markup#13]
Enables the user to easily add a 360° video to their scene.

User can specify:

* URL of source video to be loaded
* Name of clip (will be displayed by the controls)
* Type of source video, eg ogg, mp4. *Is this necessary?*
* Looping playback (true/false)
* Auto playback (true/false)
* UI controls (true/false)

Default playback controls are included.

**Comment by jcarpenter** [comment]
Fork eleVR player for this component? Or just start with simple WebGL <video> texture on Three.js sphere?

**Comment by cvan** [comment]
> Type of source video, eg ogg, mp4. Is this necessary?

nope, it's not

**Comment by cvan** [comment]
https://github.com/hawksley/eleVR-Web-Player is good but it's lacking VR controls.

I'd really recommend everyone check out [Vrideo](www.vrideo.com/embed/mYNVcD6?t=0)'s HUD video controls - I like 'em. though their code doesn't appear to be publicly open source in a readable format anywhere.

https://github.com/littlstar/axis is another player. I couldn't get it working locally, but it drives http://littlstar.com/ and it looks pretty complete, organised, and uses three.js.

<hr>

Do we want to file a separate issue for video controls?

**Comment by nickdesaulniers** [comment]
oops, I mixed this up with #7

**Comment by jcarpenter** [comment]
Done.
