### ISSUE TITLE
Add video player component

### ISSUE THREAD

**Issue by jcarpenter** [vr-components/vr-markup#7]
User can specify:

* Source URL
* Type, eg ogg, mp4 (is this necessary?)
* Loop (true/false)
* Auto playback (true/false)
* UI controls (true/false) 
* Width/height of video? Or `scale` instead, while preserving aspect ratio?

**Comment by jcarpenter** [comment]
First version of this is in place. Will kick tires on and follow up. Code implies user can set width/height. Seems the ideal would be to derive the width/height of the plane geometry from the width/height of the source clip if that information is available to us. User might then have a scale value to adjust the clip size up or down, while maintaining the aspect ratio.

**Comment by nickdesaulniers** [comment]
fixed in #17 follow ups in #18
